# Generated by Django 5.0.3 on 2024-03-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_collection', '0002_electronicwastetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewastecollection',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ewastecollection',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ewastecollection',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
