# Generated by Django 5.0.3 on 2024-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste_collection', '0003_ewastecollection_visibility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ewastecollection',
            old_name='visibility',
            new_name='visible',
        ),
        migrations.AlterField(
            model_name='ewastecollection',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
